openapi: "3.0.2"
info:
  title: TODO API title
  version: "1.0"
  description: TODO APIのドキュメントです
servers:
  - url: https://api.server.test/v1
paths:
  /health:
    get:
      responses:
        '200':
          description: OK
